# Change these first
owner: TheBlankness # Your GitHub organization or username, where this repository lives
repo: uptime-lawcloud # The name of this repository

sites:
  - name: Uptime Kuma
    url: status.lawcloud.page
  - name: LawDrive Cloud
    url: lawdrive.lawcloud.page
  - name: Truenas WebUI
    url: truenas.lawcloud.page
  - name: Doujin Server
    url: doujin-server.lawcloud.page
  - name: Law Blog
    url: blog.lawcloud.page

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.lawcloud.page
  # baseUrl: /your-repo-name
  logoUrl: https://lawdrive.lawcloud.page/apps/files_sharing/publicpreview/387q74FHZ9SDH87?file=/&fileId=5220&x=2560&y=1440&a=true
  name: Lawcloud Status
  introTitle: "**Lawcloud** is the self hosting hobby project built by Lawknight"
  introMessage: Welcome to check out if any of the my services go down
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
